#!/data/data/com.termux/files/usr/bin/bash

typeset -A taskArray

while IFS== read -r key value; do
    taskArray["$key"]="$value"
done < <(task $1 export | jq -r '.[] | to_entries | .[] | .key + "=" + (.value|tostring)')

newDescription=$(termux-dialog text -i "${taskArray[description]}" -t "Modify task" | jq '.text')

task ${taskArray[uuid]} modify $newDescription 
