#!/data/data/com.termux/files/usr/bin/bash

description=$(termux-dialog text -t "Task Description" | jq -r .text)

echo $description

date=$(./termux-dialog date -t "Task Due" -d "YYY-MM-dd")

time=$(./termux-dialog time -t "Time of Task Due")

if [[ $(echo $date | jq -r .code) -gt -2 ]] ; then
	duedate="due:$(echo $date | jq -r .text)"
fi

if [[ $(echo $time | jq -r .code) -gt -2 ]] ; then
	duetime="$(echo $time | jq -r .text) rc.dateformat:Y-M-DTH:N:S""
fi

echo "$description $duedate$duetime" 
