#!/data/data/com.termux/files/usr/bin/sh

date_format(){
  date -d "$(echo $1 | sed -r 's/(.*)T(..)(..)(..)/\1 \2:\3:\4/')"
}


task status:pending or status:active export | jq -c '.[]' | while read i; do
	typeset -A task

	while IFS== read -r key value; do
	  task["$key"]="$value"
	done < <(echo "$i" | jq -r 'to_entries  | .[] | .key + "=" + (.value|tostring)') 

	typeset -p task


	content="Status ${task[status]} "
	if [ -n "${task[project]}" ] ; then
	  content+="Project: ${task[project]}"
	fi

	if [ -n "${task[due]}" ] ; then
	  content+="Due: $(date_format ${task[due]})"
	fi


	notification="--title '${task[description]}' --id '${task[uuid]}'"
	notification+="--button1 'Done' --button1-action='termux-notification-remove ${task[uuid]} && task done ${task[uuid]}'"
 	notification+="--button2='modify' --button2-action='modify-task' --content '$content'"


	termux-notification $notification
done

