#!/data/data/com.termux/files/usr/bin/bash

date_format(){
  date -I -d "$(echo $1 | sed -r 's/(....)(..)(..)T(..)(..)(..)Z/\1-\2-\3 \4:\5:\6/')"
}


task status:pending or status:active export | jq -c '.[]' | while read i; do
	typeset -A task

	while IFS== read -r key value; do
	  task["$key"]="$value"
	done < <(echo "$i" | jq -r 'to_entries  | .[] | .key + "=" + (.value|tostring)') 


	content="Status ${task[status]} "
	if [ -n "${task[project]}" ] ; then
	  content+="Project: ${task[project]}/n \n"
	fi

	if [ -n "${task[due]}" ] ; then
	  content+="Due: $(date_format ${task[due]})"
	fi


	notification="termux-notification --title \"${task[description]}\" --id \"${task[uuid]}\""
 	notification="$notification --button1 \"Done\" --button1-action \"termux-notification-remove ${task[uuid]} && task done ${task[uuid]}\""
 	notification="$notification --button2 \"Modify\" --button2-action \"modify-task\" --content \"$content\""

	echo $notification

	eval $notification
done

