/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Android, arm64, clang */
/* Command for C compiler:
   clang -c  -w  -I/data/data/com.termux/files/usr/lib/nim/lib -o /data/data/com.termux/files/home/termux-taskwarrior/nimcache/stdlib_options.o /data/data/com.termux/files/home/termux-taskwarrior/nimcache/stdlib_options.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Option_kNYtf5W4aoHdgEo0sp9apug tyObject_Option_kNYtf5W4aoHdgEo0sp9apug;
typedef struct tyObject_RegexMatch_oPPB69cdxczJjcR9bTXyP9adg tyObject_RegexMatch_oPPB69cdxczJjcR9bTXyP9adg;
typedef struct tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw;
typedef struct tySequence_j4kOc9bUVO1cCwwySme44kA tySequence_j4kOc9bUVO1cCwwySme44kA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ;
typedef struct tyObject_Table_zjMaDBasw1LnKbj11akpfw tyObject_Table_zjMaDBasw1LnKbj11akpfw;
typedef struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og tySequence_pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tyObject_HSlice_UT1eYHF4syHhPinmd132yA tyObject_HSlice_UT1eYHF4syHhPinmd132yA;
typedef struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ;
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q {
tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA val;
NIM_BOOL has;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_RegexMatch_oPPB69cdxczJjcR9bTXyP9adg {
tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern;
NimStringDesc* str;
tySequence_j4kOc9bUVO1cCwwySme44kA* pcreMatchBounds;
};
struct tyObject_Option_kNYtf5W4aoHdgEo0sp9apug {
tyObject_RegexMatch_oPPB69cdxczJjcR9bTXyP9adg val;
NIM_BOOL has;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Table_zjMaDBasw1LnKbj11akpfw {
tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* data;
NI counter;
};
struct tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw {
NimStringDesc* pattern;
tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* pcreObj;
tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* pcreExtra;
tyObject_Table_zjMaDBasw1LnKbj11akpfw captureNameToId;
};
struct tyObject_HSlice_UT1eYHF4syHhPinmd132yA {
int a;
int b;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A {
char dummy;
};
struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ {
long flags;
void* study_data;
long match_limit;
void* callout_data;
void* tables;
long match_limit_recursion;
void* mark;
void* executable_jit;
};
struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_j4kOc9bUVO1cCwwySme44kA {
  TGenericSeq Sup;
  tyObject_HSlice_UT1eYHF4syHhPinmd132yA data[SEQ_DECL_SIZE];
};
struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og {
  TGenericSeq Sup;
  tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_eXRJfpyBfU7v2CwA4NAsjQ_2)(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q self);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_E31uzfKZFyNg6dDBfxT70Q)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_lMQI9caA3R6B9cgJwQUsPK9bw_2)(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug* self);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
TNimType NTI_bf8oYOS2OmekHPekjQ7N3g_;
TNimType NTI_E31uzfKZFyNg6dDBfxT70Q_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_s9aUgV3CLzEP2bYCJpb5r7Q_;
extern TNimType NTI_x7qpDivRIi6zcMSMsudNPA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_kNYtf5W4aoHdgEo0sp9apug_;
extern TNimType NTI_oPPB69cdxczJjcR9bTXyP9adg_;
extern TNimType NTI_j4kOc9bUVO1cCwwySme44kA_;
STRING_LITERAL(TM_4DNs4bMUkswhWc4o4dM9bbg_2, "Can\'t obtain a value from a `none`", 34);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q, some_s9ciZ4Ec7kD4BDdiZ7yP6Vw)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA val) {
	tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q result;
	nimfr_("some", "options.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(81, "options.nim");
	result.has = NIM_TRUE;
	nimln_(82, "options.nim");
	result.val = val;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q, none_1k2GTbqy9a9bDbSA2KdjC67g)(void) {
	tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q result;
	nimfr_("none", "options.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(86, "options.nim");
	result.has = NIM_FALSE;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_eXRJfpyBfU7v2CwA4NAsjQ)(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q self) {
	NIM_BOOL result;
	nimfr_("isSome", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(89, "options.nim");
	result = self.has;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_eXRJfpyBfU7v2CwA4NAsjQ_2)(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q self) {
	NIM_BOOL result;
	nimfr_("isNone", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(92, "options.nim");
	result = !(self.has);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_E31uzfKZFyNg6dDBfxT70Q)(void* p, NI op) {
	tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g* a;
	a = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, get_0aoUITsmMAtzBZLmRHJ9b1A)(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q self) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("get", "options.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(100, "options.nim");
	nimln_(102, "options.nim");
	{
		NIM_BOOL T3_;
		tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g* T6_;
		NimStringDesc* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone_eXRJfpyBfU7v2CwA4NAsjQ_2(self);
		if (!T3_) goto LA4_;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*)0;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*) newObj((&NTI_E31uzfKZFyNg6dDBfxT70Q_), sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI_bf8oYOS2OmekHPekjQ7N3g_);
		T7_ = (NimStringDesc*)0;
		T7_ = (*T6_).Sup.Sup.message; (*T6_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_2));
		if (T7_) nimGCunrefNoCycle(T7_);
		nimln_(103, "options.nim");
		raiseException((Exception*)T6_, "UnpackError:ObjectType");
	}
	LA4_: ;
	result = self.val;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, some_f21orKBe1LoeHJDpj9cnm3A)(tyObject_RegexMatch_oPPB69cdxczJjcR9bTXyP9adg val, tyObject_Option_kNYtf5W4aoHdgEo0sp9apug* Result) {
	nimfr_("some", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_kNYtf5W4aoHdgEo0sp9apug_));
	nimln_(81, "options.nim");
	(*Result).has = NIM_TRUE;
	nimln_(82, "options.nim");
	unsureAsgnRef((void**) (&(*Result).val.pattern), val.pattern);
	unsureAsgnRef((void**) (&(*Result).val.str), copyString(val.str));
	genericSeqAssign((&(*Result).val.pcreMatchBounds), val.pcreMatchBounds, (&NTI_j4kOc9bUVO1cCwwySme44kA_));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, none_4g8u9cqSozyZXylrYfMcXiw)(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug* Result) {
	nimfr_("none", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_kNYtf5W4aoHdgEo0sp9apug_));
	nimln_(86, "options.nim");
	(*Result).has = NIM_FALSE;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_lMQI9caA3R6B9cgJwQUsPK9bw)(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug* self) {
	NIM_BOOL result;
	nimfr_("isSome", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(89, "options.nim");
	result = (*self).has;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_lMQI9caA3R6B9cgJwQUsPK9bw_2)(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug* self) {
	NIM_BOOL result;
	nimfr_("isNone", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(92, "options.nim");
	result = !((*self).has);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, get_PWs9aqJ6PoD1WcZ9cFS0lj7g)(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug* self, tyObject_RegexMatch_oPPB69cdxczJjcR9bTXyP9adg* Result) {
	nimfr_("get", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_oPPB69cdxczJjcR9bTXyP9adg_));
	nimln_(100, "options.nim");
	nimln_(102, "options.nim");
	{
		NIM_BOOL T3_;
		tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g* T6_;
		NimStringDesc* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone_lMQI9caA3R6B9cgJwQUsPK9bw_2(self);
		if (!T3_) goto LA4_;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*)0;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*) newObj((&NTI_E31uzfKZFyNg6dDBfxT70Q_), sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI_bf8oYOS2OmekHPekjQ7N3g_);
		T7_ = (NimStringDesc*)0;
		T7_ = (*T6_).Sup.Sup.message; (*T6_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_2));
		if (T7_) nimGCunrefNoCycle(T7_);
		nimln_(103, "options.nim");
		raiseException((Exception*)T6_, "UnpackError:ObjectType");
	}
	LA4_: ;
	unsureAsgnRef((void**) (&(*Result).pattern), (*self).val.pattern);
	unsureAsgnRef((void**) (&(*Result).str), copyString((*self).val.str));
	genericSeqAssign((&(*Result).pcreMatchBounds), (*self).val.pcreMatchBounds, (&NTI_j4kOc9bUVO1cCwwySme44kA_));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsInit000)(void) {
	nimfr_("options", "options.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_optionsDatInit000)(void) {
static TNimNode* TM_4DNs4bMUkswhWc4o4dM9bbg_3[2];
static TNimNode* TM_4DNs4bMUkswhWc4o4dM9bbg_4[2];
static TNimNode TM_4DNs4bMUkswhWc4o4dM9bbg_0[7];
NTI_bf8oYOS2OmekHPekjQ7N3g_.size = sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g);
NTI_bf8oYOS2OmekHPekjQ7N3g_.kind = 17;
NTI_bf8oYOS2OmekHPekjQ7N3g_.base = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].len = 0; TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].kind = 2;
NTI_bf8oYOS2OmekHPekjQ7N3g_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[0];
NTI_E31uzfKZFyNg6dDBfxT70Q_.size = sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*);
NTI_E31uzfKZFyNg6dDBfxT70Q_.kind = 22;
NTI_E31uzfKZFyNg6dDBfxT70Q_.base = (&NTI_bf8oYOS2OmekHPekjQ7N3g_);
NTI_E31uzfKZFyNg6dDBfxT70Q_.marker = Marker_tyRef_E31uzfKZFyNg6dDBfxT70Q;
NTI_s9aUgV3CLzEP2bYCJpb5r7Q_.size = sizeof(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q);
NTI_s9aUgV3CLzEP2bYCJpb5r7Q_.kind = 18;
NTI_s9aUgV3CLzEP2bYCJpb5r7Q_.base = 0;
NTI_s9aUgV3CLzEP2bYCJpb5r7Q_.flags = 3;
TM_4DNs4bMUkswhWc4o4dM9bbg_3[0] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[2];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].offset = offsetof(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q, val);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].typ = (&NTI_x7qpDivRIi6zcMSMsudNPA_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].name = "val";
TM_4DNs4bMUkswhWc4o4dM9bbg_3[1] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[3];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[3].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[3].offset = offsetof(tyObject_Option_s9aUgV3CLzEP2bYCJpb5r7Q, has);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[3].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[3].name = "has";
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].len = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].kind = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].sons = &TM_4DNs4bMUkswhWc4o4dM9bbg_3[0];
NTI_s9aUgV3CLzEP2bYCJpb5r7Q_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[1];
NTI_kNYtf5W4aoHdgEo0sp9apug_.size = sizeof(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug);
NTI_kNYtf5W4aoHdgEo0sp9apug_.kind = 18;
NTI_kNYtf5W4aoHdgEo0sp9apug_.base = 0;
NTI_kNYtf5W4aoHdgEo0sp9apug_.flags = 2;
TM_4DNs4bMUkswhWc4o4dM9bbg_4[0] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[5];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].offset = offsetof(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug, val);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].typ = (&NTI_oPPB69cdxczJjcR9bTXyP9adg_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].name = "val";
TM_4DNs4bMUkswhWc4o4dM9bbg_4[1] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[6];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[6].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[6].offset = offsetof(tyObject_Option_kNYtf5W4aoHdgEo0sp9apug, has);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[6].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[6].name = "has";
TM_4DNs4bMUkswhWc4o4dM9bbg_0[4].len = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[4].kind = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[4].sons = &TM_4DNs4bMUkswhWc4o4dM9bbg_4[0];
NTI_kNYtf5W4aoHdgEo0sp9apug_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[4];
}

